In [1]:
import pandas as pd

import numpy as np

startup_2021 = pd.read_csv(r'C:\Users\User\Desktop\AZUBI AFRICA\Projects\LP 1\startup_funding2021.csv')

startup_2021

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage
0,Unbox Robotics,2019.0,Bangalore,AI startup,Unbox Robotics builds on-demand AI-driven ware...,"Pramod Ghadge, Shahid Memon","BEENEXT, Entrepreneur First","$1,200,000",Pre-series A
1,upGrad,2015.0,Mumbai,EdTech,UpGrad is an online higher education platform.,"Mayank Kumar, Phalgun Kompalli, Ravijot Chugh,...","Unilazer Ventures, IIFL Asset Management","$120,000,000",NaN
2,Lead School,2012.0,Mumbai,EdTech,LEAD School offers technology based school tra...,"Smita Deorah, Sumeet Mehta","GSV Ventures, Westbridge Capital","$30,000,000",Series D
3,Bizongo,2015.0,Mumbai,B2B E-commerce,Bizongo is a business-to-business online marke...,"Aniket Deb, Ankit Tomar, Sachin Agrawal","CDC Group, IDG Capital","$51,000,000",Series C
4,FypMoney,2021.0,Gurugram,FinTech,"FypMoney is Digital NEO Bank for Teenagers, em...",Kapil Banwari,"Liberatha Kallat, Mukesh Yadav, Dinesh Nagpal","$2,000,000",Seed
...,...,...,...,...,...,...,...,...,...
1204,Gigforce,2019.0,Gurugram,Staffing & Recruiting,A gig/on-demand staffing company.,"Chirag Mittal, Anirudh Syal",Endiya Partners,$3000000,Pre-series A
1205,Vahdam,2015.0,New Delhi,Food & Beverages,VAHDAM is among the world’s first vertically i...,Bala Sarda,IIFL AMC,$20000000,Series D
1206,Leap Finance,2019.0,Bangalore,Financial Services,International education loans for high potenti...,"Arnav Kumar, Vaibhav Singh",Owl Ventures,$55000000,Series C
1207,CollegeDekho,2015.0,Gurugram,EdTech,"Collegedekho.com is Student’s Partner, Friend ...",Ruchir Arora,"Winter Capital, ETS, Man Capital",$26000000,Series B
1208,WeRize,2019.0,Bangalore,Financial Services,India’s first socially distributed full stack ...,"Vishal Chopra, Himanshu Gupta","3one4 Capital, Kalaari Capital",$8000000,Series A

In [2]:
# STARTUP_2021 PROCESSING

startup_2021.head(100)

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage
0,Unbox Robotics,2019.0,Bangalore,AI startup,Unbox Robotics builds on-demand AI-driven ware...,"Pramod Ghadge, Shahid Memon","BEENEXT, Entrepreneur First","$1,200,000",Pre-series A
1,upGrad,2015.0,Mumbai,EdTech,UpGrad is an online higher education platform.,"Mayank Kumar, Phalgun Kompalli, Ravijot Chugh,...","Unilazer Ventures, IIFL Asset Management","$120,000,000",NaN
2,Lead School,2012.0,Mumbai,EdTech,LEAD School offers technology based school tra...,"Smita Deorah, Sumeet Mehta","GSV Ventures, Westbridge Capital","$30,000,000",Series D
3,Bizongo,2015.0,Mumbai,B2B E-commerce,Bizongo is a business-to-business online marke...,"Aniket Deb, Ankit Tomar, Sachin Agrawal","CDC Group, IDG Capital","$51,000,000",Series C
4,FypMoney,2021.0,Gurugram,FinTech,"FypMoney is Digital NEO Bank for Teenagers, em...",Kapil Banwari,"Liberatha Kallat, Mukesh Yadav, Dinesh Nagpal","$2,000,000",Seed
...,...,...,...,...,...,...,...,...,...
95,TartanSense,2015.0,Bangalore,Information Technology,TartanSense unlocks value for small farm holde...,Jaisimha Rao,"FMC, Omnivore, Blume Ventures",$5000000,NaN
96,Bewakoof,2012.0,Mumbai,Apparel & Fashion,Bewakoof is a lifestyle fashion brand that mak...,Prabhkiran Singh,InvestCorp,$8000000,NaN
97,Kirana247,2018.0,New Delhi,Logistics & Supply Chain,An on-demand FMCG supply chain company leverag...,"Tarun Jiwarajka, Pankhuri Jiwarajka",NaN,$1000000,NaN
98,FanPlay,2020.0,Computer Games,Computer Games,A real money game app specializing in trivia g...,YC W21,"Pritesh Kumar, Bharat Gupta",Upsparks,$1200000
99,NeoDocs,2020.0,Mumbai,Healthtech,Neodocs is a part of India's prominent Social ...,"Nikunj Malpani, Anurag Meena, Pratik Lodha","Y Combinator, 9Unicorns, Titan Capital",$Undisclosed,NaN

In [3]:
startup_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1209 entries, 0 to 1208
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Company/Brand  1209 non-null   object
 1   Founded        1208 non-null   float64
 2   HeadQuarter    1208 non-null   object
 3   Sector         1209 non-null   object
 4   What it does   1209 non-null   object
 5   Founders       1205 non-null   object
 6   Investor       1147 non-null   object
 7   Amount($)      1206 non-null   object
 8   Stage          781 non-null    object
dtypes: float64(1), object(8)
memory usage: 85.1+ KB

In [4]:
startup_2021.isnull().sum()

Company/Brand      0
Founded            1
HeadQuarter        1
Sector             0
What it does       0
Founders           4
Investor          62
Amount($)          3
Stage            428
dtype: int64

In [5]:
# COLUMN BY COLUMN CLEANING

# FOUNDED COLUMN CLEANING


# CHECKING FOR MISSING VALUES
startup_2021['Founded'].isna().sum()

1

### the Founded Column has only 1 nan value. We can use the mean or the mode to fill it

In [6]:
startup_2021['Founded'].unique()

array([2019., 2015., 2012., 2021., 2014., 2018., 2016., 2020., 2010.,
       2017., 1993., 2008., 2013., 1999., 1989., 2011.,   nan, 2009.,
       2002., 1994., 2006., 2000., 2007., 1978., 2003., 1998., 1991.,
       1984., 2004., 2005., 1963.])

In [7]:
# SETTING THE DATATYPE FOR THE FOUNDED COLUMN TO STRING

startup_2021['Founded'] = startup_2021['Founded'].replace(np.nan, 0)

startup_2021['Founded'] = startup_2021['Founded'].astype(int)

startup_2021['Founded']

0       2019
1       2015
2       2012
3       2015
4       2021
        ...
1204    2019
1205    2015
1206    2019
1207    2015
1208    2019
Name: Founded, Length: 1209, dtype: int32

In [8]:
# We are filling the "NAN" with the mean 

# calculating the mean and repalcing "0" with it

mean_val = startup_2021['Founded'].mean()

mean_val

2014.987593052109

In [9]:
startup_2021.Founded = startup_2021.Founded.replace("0",2015)

startup_2021.Founded

0       2019
1       2015
2       2012
3       2015
4       2021
        ...
1204    2019
1205    2015
1206    2019
1207    2015
1208    2019
Name: Founded, Length: 1209, dtype: int32

In [10]:
startup_2021.Founded.isna().sum()

0

### Our Founded Column is clean now.

In [11]:
# CLEANING OF THE HEADQUARTERS COLUMN

startup_2021['HeadQuarter'].unique()

array(['Bangalore', 'Mumbai', 'Gurugram', 'New Delhi', 'Hyderabad',
       'Jaipur', 'Ahmadabad', 'Chennai', nan,
       'Small Towns, Andhra Pradesh', 'Goa', 'Rajsamand', 'Ranchi',
       'Faridabad, Haryana', 'Gujarat', 'Pune', 'Thane', 'Computer Games',
       'Cochin', 'Noida', 'Chandigarh', 'Gurgaon', 'Vadodara',
       'Food & Beverages', 'Pharmaceuticals\t#REF!', 'Gurugram\t#REF!',
       'Kolkata', 'Ahmedabad', 'Mohali', 'Haryana', 'Indore', 'Powai',
       'Ghaziabad', 'Nagpur', 'West Bengal', 'Patna', 'Samsitpur',
       'Lucknow', 'Telangana', 'Silvassa', 'Thiruvananthapuram',
       'Faridabad', 'Roorkee', 'Ambernath', 'Panchkula', 'Surat',
       'Coimbatore', 'Andheri', 'Mangalore', 'Telugana', 'Bhubaneswar',
       'Kottayam', 'Beijing', 'Panaji', 'Satara', 'Orissia', 'Jodhpur',
       'New York', 'Santra', 'Mountain View, CA', 'Trivandrum',
       'Jharkhand', 'Kanpur', 'Bhilwara', 'Guwahati',
       'Online Media\t#REF!', 'Kochi', 'London',
       'Information Technology & Services', 'The Nilgiris', 'Gandhinagar'],
      dtype=object)

In [12]:
# checking the missing value

startup_2021['HeadQuarter'].isna().sum()

1

### It has only one missing value

In [13]:
# Replacing NAN values with "Undefined"

headquarters_2021 = startup_2021.HeadQuarter.isnull()

headquarters_2021

0       False
1       False
2       False
3       False
4       False
        ...
1204    False
1205    False
1206    False
1207    False
1208    False
Name: HeadQuarter, Length: 1209, dtype: bool

In [14]:
# Replacing the 'NAN' value with Keyword "Undefined"

for i in range(len(headquarters_2021)):
    if headquarters_2021[i] == True:
        startup_2021.HeadQuarter[i] = "Undefined"

C:\Users\User\AppData\Local\Temp\ipykernel_15068\4004753485.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  startup_2021.HeadQuarter[i] = "Undefined"

In [15]:
startup_2021.HeadQuarter.isnull().sum()

0

In [16]:
startup_2021['HeadQuarter'] = startup_2021['HeadQuarter'].str.replace('Pharmaceuticals\t#REF!', 'Pharmaceuticals')

startup_2021['HeadQuarter'] = startup_2021['HeadQuarter'].str.replace('Gurugram\t#REF!', 'Gurugram')

startup_2021['HeadQuarter'] = startup_2021['HeadQuarter'].str.replace('Online Media\t#REF!', 'Online Media')


startup_2021

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage
0,Unbox Robotics,2019,Bangalore,AI startup,Unbox Robotics builds on-demand AI-driven ware...,"Pramod Ghadge, Shahid Memon","BEENEXT, Entrepreneur First","$1,200,000",Pre-series A
1,upGrad,2015,Mumbai,EdTech,UpGrad is an online higher education platform.,"Mayank Kumar, Phalgun Kompalli, Ravijot Chugh,...","Unilazer Ventures, IIFL Asset Management","$120,000,000",NaN
2,Lead School,2012,Mumbai,EdTech,LEAD School offers technology based school tra...,"Smita Deorah, Sumeet Mehta","GSV Ventures, Westbridge Capital","$30,000,000",Series D
3,Bizongo,2015,Mumbai,B2B E-commerce,Bizongo is a business-to-business online marke...,"Aniket Deb, Ankit Tomar, Sachin Agrawal","CDC Group, IDG Capital","$51,000,000",Series C
4,FypMoney,2021,Gurugram,FinTech,"FypMoney is Digital NEO Bank for Teenagers, em...",Kapil Banwari,"Liberatha Kallat, Mukesh Yadav, Dinesh Nagpal","$2,000,000",Seed
...,...,...,...,...,...,...,...,...,...
1204,Gigforce,2019,Gurugram,Staffing & Recruiting,A gig/on-demand staffing company.,"Chirag Mittal, Anirudh Syal",Endiya Partners,$3000000,Pre-series A
1205,Vahdam,2015,New Delhi,Food & Beverages,VAHDAM is among the world’s first vertically i...,Bala Sarda,IIFL AMC,$20000000,Series D
1206,Leap Finance,2019,Bangalore,Financial Services,International education loans for high potenti...,"Arnav Kumar, Vaibhav Singh",Owl Ventures,$55000000,Series C
1207,CollegeDekho,2015,Gurugram,EdTech,"Collegedekho.com is Student’s Partner, Friend ...",Ruchir Arora,"Winter Capital, ETS, Man Capital",$26000000,Series B
1208,WeRize,2019,Bangalore,Financial Services,India’s first socially distributed full stack ...,"Vishal Chopra, Himanshu Gupta","3one4 Capital, Kalaari Capital",$8000000,Series A

In [17]:
startup_2021.isna().sum()

Company/Brand      0
Founded            0
HeadQuarter        0
Sector             0
What it does       0
Founders           4
Investor          62
Amount($)          3
Stage            428
dtype: int64

### Now, the Headquarters Column is great.


## LET'S LOOK AT THE FOUNDERS COLUMN TO CLEAN IT

In [18]:
# checking for missing values

startup_2021['Founders'].isna().sum()

4

In [19]:
# It has only 4 missing values

# We are going to replace them with Keyword "Undefined"

startup_2021['Founders'].unique()

array(['Pramod Ghadge, Shahid Memon',
       'Mayank Kumar, Phalgun Kompalli, Ravijot Chugh, Ronnie Screwvala',
       'Smita Deorah, Sumeet Mehta', ..., 'Bala Sarda',
       'Arnav Kumar, Vaibhav Singh', 'Vishal Chopra, Himanshu Gupta'],
      dtype=object)

In [20]:
founders_2021 = startup_2021.Founders.isnull()

founders_2021

0       False
1       False
2       False
3       False
4       False
        ...
1204    False
1205    False
1206    False
1207    False
1208    False
Name: Founders, Length: 1209, dtype: bool

In [21]:
# Replacing the '...' value with Keyword "Undefined"

for i in range(len(founders_2021)):
    if founders_2021[i] == True:
        startup_2021.Founders[i] = "Undefined"

C:\Users\User\AppData\Local\Temp\ipykernel_15068\2680666504.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  startup_2021.Founders[i] = "Undefined"

In [22]:
startup_2021.Founders.isnull().sum()

0

### The Founder column is Cleaned now


# CLEANING OF THE INVESTOR COLUMN

In [23]:
startup_2021.Investor.info()

<class 'pandas.core.series.Series'>
RangeIndex: 1209 entries, 0 to 1208
Series name: Investor
Non-Null Count  Dtype
--------------  -----
1147 non-null   object
dtypes: object(1)
memory usage: 9.6+ KB

In [24]:
investors_2021 = startup_2021.Investor.isna().sum()

investors_2021

62

In [25]:
startup_2021.Investor.unique()

array(['BEENEXT, Entrepreneur First',
       'Unilazer Ventures, IIFL Asset Management',
       'GSV Ventures, Westbridge Capital', 'CDC Group, IDG Capital',
       'Liberatha Kallat, Mukesh Yadav, Dinesh Nagpal', 'Vy Capital',
       'CIIE.CO, KIIT-TBI', 'Inflection Point Ventures',
       'Inflexor Ventures', nan,
       '9Unicorns Accelerator Fund, Metaform Ventures',
       'SucSEED Indovation, IIM Calcutta Innovation Park',
       'Safe Planet Medicare', 'Impact Partners, C4D Partners',
       'Tiger Global Management, InnoVen Capital', 'Novo Tellus Capital',
       'Raintree Family Office, ADB arm',
       'Mumbai Angels, Narendra Shyamsukha', 'Paradigm, Kunal Shah',
       'Matrix Partners India, GIC', 'Chiratae Ventures, JAFCO Asia',
       'Mumbai Angels Network, Expert DOJO', 'GVFL',
       'Kotak Mahindra Bank, FMO', 'Kalaari Capital',
       'NB Ventures, IAN Fund',
       'Sequoia Capital India, Hummingbird Ventures',
       'Gaurav Munjal, Snehil Khanor', 'JITO Angel Network, SOSV',
       'Chiratae Ventures, YourNest Venture Capital', 'STRIVE VC',
       'Venture Catalysts', 'Jaipuria Family Office', 'Amazon',
       'Riso Capital', 'MTG Ventures',
       'Qualcomm Ventures, Warburg Pincus', '9Unicorns', 'Morgan Stanley',
       'Alfa Ventures, Agility Venture Partners',
       'Stellaris Venture Partners, Ramakant Sharma', 'Spanache',
       'DSG Consumer Partners, Saama Capital', 'Hindustan Media Ventures',
       'Stellaris Venture Partners, Omidyar Network India, Flourish Ventures',
       'Angelbay Holdings, Faad Network',
       'Alteria Capital, Chiratae Ventures',
       'WaterBridge Ventures, Info Edge',
       'Carmignac, Falcon Edge Capital', 'Vaibhav Domkundwar, Kunal Shah',
       'Chiratae Ventures, Bharat Innovation Fund',
       'Acko Technology, Services, LetsVenture',
       'Bertelsmann India Investments, Fullerton Financial Holdings',
       'Dragoneer Investment Group, Tiger Global Management',
       'http://100x.vc/',
       'TPG Growth, Caisse de Depot et Placement du Quebec',
       'Centrum Financial Services', 'Chiratae Ventures, BEENEXT',
       'Harsha Bhogle', 'GetVantage, Prakash Katama',
       'Tiger Global Management, Y Combinator Continuity Fund',
       'Michael & Susan Dell Foundation', 'Marquee fintech founders',
       'Falcon Edge India, Norwest Venture Partners',
       'SOSV, Omphalos Ventures India', 'Twitter Ventures, Pawan Munjal',
       'CitiusTech', 'Arena Holdings, Think Investments',
       'T Choithrams BVI, Ardor',
       'Kogta Financial India Limited, ICICI Bank',
       'SucSEED Venture Partners, TMT Connekt',
       'SAIF Partners, Venture Highway', 'Global Founders Capital',
       'JAFCO Asia, Chiratae Ventures', 'Y Combinator',
       'Artha Venture Fund', 'Jitendra Gupta, Amrish Rau',
       'FJ Labs, Brian Norgard', 'Indian Angel Network',
       'Jitendra Gupta, Harsh Shah',
       'Elevation Partners, Emergent Ventures',
       'Kalaari Capital, Dream Capital', 'Lumikai',
       'Matrix Partners India', 'C4D Partners', 'Bertelsmann India',
       'Iron Pillar, Nordstar, Binny Bansal',
       'FMC, Omnivore, Blume Ventures', 'InvestCorp',
       'Pritesh Kumar, Bharat Gupta',
       'Y Combinator, 9Unicorns, Titan Capital',
       'Unicorn India Ventures, SEA Fund, Devdatt Shah',
       'Matrix Partners India, Elevation Capital',
       'Avaana Capital, Orios Ventures', 'Punit Balan',
       'Y Combinator, Broom Ventures, Kunal Shah',
       'Skycatcher, AET Fund, BAce Capital, Dream Incubator, 1Up Ventures',
       'Eclear Leasing', 'First Cheque, Letsventure',
       'Sequoia Capital India, BEENEXT', 'Velocity',
       'Tribe Capital, Moore Strategic Ventures (MSV)',
       'Fireside Ventures', 'Inflection Point Ventures, ONGC',
       'Y Combinator, Incubate Fund India',
       'Titan Capital, Rockstud Capital,  John Abraham, WEH Ventures',
       'Info Edge Ventures', 'NB Ventures', 'Accel',
       'Binny Bansal, Kunal Shah', 'TradeCred', 'Unicorn India Ventures',
       'UC Inclusive Credit, Western Capital',
       'IIFL India Private Equity Fund, Smiti Holding & Trading Company',
       'Faering Capital', 'responsAbility Investments, Blue Orchard',
       'Sanchit Agarwal, Sujan Sinha, Michael Cooke',
       'CRV, Nexus Venture Partners',
       'Salesforce Ventures, Sierra Ventures, Sequoia Capital India’s Surge',
       'Micelio Fund, growX ventures',
       'IIFL Wealth, Asset Management, Northern Arc Capital',
       'Better Capital, Ashish Achrekar', 'IAN', 'Alpha Wave Incubation',
       'Point One Capital, Yatra Angel Network (YAN), Opus Consulting, Manipal Technologies.',
       'Microsoft', 'Shell Ventures, Yamaha, Kunal Shah',
       'We Founder Circle',
       'Saama Capital, DSG Consumer Partners, Sharrp Ventures',
       'Tiger Global’s Scott Schleifer', 'Elevation Capital',
       'Venture Catalysts, Auxano Capital, Venture Garage, Yoga Capital, Ah!Ventures, Lead Angels',
       'Sixth Sense Ventures', '9Unicorns, Sequoia Capital India’s Surge',
       'Anicut Angel Fund, 9 Unicorns', 'Info Edge, FalconEdge',
       'WestCap Group, Tomales Bay Capital',
       'Chiratae Ventures, Better Capital',
       'Siguler Guff, Baillie Gifford',
       'IIFL AMC, Mankind Pharma Family Office, Aroa Ventures',
       'ITI Growth Opportunities', 'Amrac Investment Trust',
       'Bhavin Turakhia', 'Amara Raja Batteries',
       'India Infoline Finance', 'Venture Highway', 'BEENEXT, Orios',
       'Axilor', 'Westbridge Capital, Tanglin Venture Partners',
       '100X.VC\ufeff,\ufeff Titan Capital, Rahul Mathur, Gaurav Mandlecha',
       'IIFL, Amicus Capital, Ananta Capital',
       'Venture Highway, Endiya Partners',
       'Verlinvest, Sequoia Capital India', 'Anicut Angel Fund',
       'Tiger Global',
       'Alphabit Fund, Fulgur Ventures, Stacks Accelerator, SBX Capital',
       'Roots Ventures, Velo Partners', 'Nexus Venture Partners',
       'Mumbai Angels Network, Huddle, Lumis Partners',
       'SucSEED Indovation Fund',
       'Potencia Ventures, Bisk Ventures, LetsVenture, Ronnie Screwvala, Arihant Patni',
       'Better Capital, First Cheque, Titan Capital', 'Evolvence Capital',
       'SARA ELGI',
       'Nubank, Global Founders Capital, Sequoia Capital India, Matrix Partners India',
       'ah! Ventures High Tables',
       'Eight Roads Ventures, Think Investments, Mankekar Family Office',
       'A91 Partners', 'Chiratae Ventures', 'Sequoia’s Surge',
       'Lead Angels, Titan Capital, Pravega Ventures',
       'Accel Partners, Elevation Capital',
       'Inflection Point Ventures, Rockstud Capital, FirstPort Capital, Bliss Flow Investments Pvt Ltd',
       'Anicut Angel Fund, Axilor Ventures',
       'Ecosystem Ventures, CMM group',
       'Mumbai Angels Network, Social Alpha', 'Disrupt ADQ, QIC',
       'Valar Ventures, IA Ventures', 'Sequoia Capital India', 'Zomato',
       'Lightspeed, Times Group, Tanglin Venture Partners',
       'Binny Bansal, Deep Kalra, Dr Ashish Gupta, Gokul Rajaram, Shirish Nadkarni',
       'Tuscan Ventures, Ohm Stock Brokers, Artha Venture Fund',
       'Signal Peak Ventures', 'Evolvence, Hero Enterprise',
       'BlueOrchard Impact Investment Managers', 'Steadview Capital',
       'MassMutual Ventures', 'YourNest VC', 'Accel India',
       'Vijay Shekhar Sharma, Ritesh Agarwal, Ankiti Bose',
       'TVS Motor, Zoho', 'IIFL Asset Management',
       'Oasis Capital, Scorpio VC, DeltaHub Capital',
       'Titan Capital, Haresh Chawla, AngelList Syndicate',
       '9Unicorns, Ashneer Grover', 'Founders Room Capital',
       '9Unicorns, ZNL', 'WEH Ventures', '$22000000', '$5000000',
       'Kunal Shah, Deepinder Goyal, Abhiraj Singh Bhal',
       'Guild Capital, RPSG Capital Ventures',
       'General Catalyst, Eight Roads Ventures, Elevation Capital',
       'NB Ventures, Earlsfield Capital', 'Varun Alagh, Sahil Barua',
       'SoftBank Vision Fund 2', 'Tribe Capital, Prime Venture Partners',
       'Jungle Ventures', 'Marquee international institutional investors',
       'Alkeon Capital', 'Y Combinator, Harvard Management',
       'Y Combinator\ufeff, \ufeffGoodwater Capital',
       'Shrishti Sahu, Umang Vohra', 'Astra Ventures, Gaurav Jaitly',
       'Capital A, Collective Artists Network',
       'Aditya Singhal, Nishant Sinha', 'Pentathlon Ventures',
       'Alpha Wave Ventures II, Tiger Global Management, SoftBank Vision Fund II',
       'KRAFTON', 'Chiratae Ventures, Lenskart Vision Fund', 'Recur Club',
       'DevX Venture Fund, Blume Founder Fund', 'Ajith Daneil',
       'Aurum Proptech', 'Y-Combinator', 'The Good Glamm Group', 'Invus',
       'Tiger Global, Prosus Ventures',
       'Shuru Up, Ankit Kedia, Arun Gupta',
       'Ankit Mehrotra, Saurabh Aggarwal', 'Sauce.vc',
       '3one4 Capital, Sixth Sense Ventures',
       'YCombinator, Justin Mateen, Pioneer Fund',
       'Sojitz Corporation, Stride Ventures',
       'IIFL Wealth, TPG Growth, Norwest Venture Partners',
       'Nabventures, Avaana Capital', 'Fluid Ventures, Mulberry Silks',
       'Rajesh Rajendran', 'Mike Novogratz, Neeraj Arora',
       'Reliance Digital Health', 'DevX Venture Fund',
       'Ritu Marya Family Office.', 'Ten Innovate',
       'Tiger Global, Sequoia Capital', 'Shark Tank India',
       'Premji Invest, Steadview Capital', 'Sequoia',
       'Apis Insurtech Fund I', 'SK Tripathi, Sanjeev Gupta',
       'Hardcastle Petrofer', 'Ocean View Investment, QED Fund',
       'Omidyar Network, Tencent Holdings',
       'ITI Growth Opportunities Fund, Unit-E Ventures',
       'InnoVen Capital, Nexus Venture Partners', 'CIIE.CO',
       'Orios Venture Partners', 'Omidyar Network India',
       'Wipro venture capital arm', 'Yuj Ventures, Sixth Sense Ventures',
       'Premji Invest, Mirae Asset Naver Asia Growth Fund, Alpine Capital',
       'Inflection Point Ventures, SucSEED Venture Partners',
       'Anas Rahman Junaid, Vinod Jose', 'Capital One, Arrowroot Capital',
       'YourNest Venture Capital', 'Incubate Fund India',
       'Kunal Shah, Greg Kidd', 'InnoVen Capital, TEAMFund',
       'Venture Catalysts, 9Unicorns Accelerator Fund',
       'Venture Highway, Rohit Bansal', 'Fresco Capital, Social Starts',
       'Y Combinator, Rebright Partners',
       'Rohit Goutamchand, India CXO Fund',
       'Rajasthan Venture Capital Fund, ACPL Exports',
       'Amplo, Insight Partners', 'Better Capital', 'Justin Mateen',
       'View Trade Holding Corp',
       'InnoVen Capital, Bertelsmann India Investments', 'ScoopWhoop',
       'Canaan Valley Capital, Glade Brook Capital Partners',
       'Vijay Shekhar Sharma, Dr Ritesh Malik',
       'RTP Global, Harshil Mathur', 'Paragon Partners, NABVENTURES',
       'EXPERT DOJO', 'Saama Capital, India Quotient',
       'InCred Financial Services, Vivriti Capital, Northern Arc Capital',
       'ah! Ventures', 'Somak Ghosh, M V Nair', 'Wurk',
       'Plutus Wealth Management, Turtle Entertainment',
       'Ambiga Subramanian, Goutham Ekollu', 'Accel, Owl Ventures',
       'Rajan Anadan', 'Jesse Lucas',
       'IDFC Private Equity, Bessemer Venture Partners',
       'Sequoia Capital India, Accel',
       'Venture Catalysts, Tahseen Consulting', 'Equanimity Ventures',
       'BlueOrchard Finance S A, Gojo & Company',
       'Better Capital, Titan Capital', 'Gojo & Company', 'Mumbai Angels',
       'Pegasus Tech Ventures, Base Partners', '3one4 Capital, Accel',
       'Hitesh Oberoi, Lightbox', 'YES Bank', 'Campus Fund',
       'Hyperplane Venture Capital', 'Matrix Partners India, RTP Global',
       'Info Edge, Ruizheng Investment', 'Quess Corp India',
       'Sunil Kumar Singhvi, 9Unicorns Accelerator Fund',
       'India Accelerator’s Angel Investor Network', 'Shell Foundation',
       'Jimmy Singh', 'Kunal Shah, Deepak Abbot', 'Accel, Nexus Venture',
       'Singapore Angel Network, Artha India Ventures',
       'Starfish Growth Partners, Investpad', 'Hashed', 'Titan Capital',
       "Zerodha's Rainmatter Capital, Better Capital",
       'Sixth Sense Ventures, Colgate Palmolive',
       'Lightbox, Evolvence India Fund', 'Tomorrow Capital',
       'Inflection Point Ventures, DLabs',
       'InnoVen Capital, Steadview Capital', 'BlackSoil Capital',
       'PointOne Capital, Core91 VC', 'A91 Partners, Faering Capital',
       'Blockchain Capital, SBI Ven Capital',
       'Baring Private Equity Partners India, Talbros',
       'Sequoia Capital India, 3one4 Capital',
       'Prosus Ventures, RTP Global',
       'U.S. International Development Finance Corp, responsAbility',
       'Binance Labs, Zee Prime Capital', 'RP-Sanjiv Goenka Group',
       'IvyCap Ventures', 'Zone Startups In', 'Blue Ashva Capital',
       'Ribbit Capital, Kunal Shah', 'Ecom Express', 'InnoVen Capital',
       'Satish Grampurohit', 'Amit Singhal, Raine Ventures',
       'Tiger Global, Dragoneer Investment Group, Steadview Capital, General Atlantic',
       'CDC Group, Aavishkaar Venture Capital', 'GSF, Pras Hanuma',
       'Ajat Hukkoo, Piyush Chaplot', 'Mumbai Angels, Amitesh Pandey',
       'Think Investments',
       'Nexus Venture Partners, 23 High Networth Individuals (HNIs)',
       'Yatra Angel Network, BEENEXT',
       'Orios Venture Partners, Matrix Partners India', 'Trishneet Arora',
       'ContCentric', 'Siana Capital', 'DST Global, General Catalyst',
       'Anthill Ventures', 'InnoVen Capital, InnoVen Capita',
       '3one4 Capital, DSP Group', 'Enzia Ventures, AngelList',
       'Steadview Capital, Insight Partners',
       'Invested Development, Pratithi Investment Trust',
       'Octahedron Capital, Moonstone Capital',
       'Dhianu Das, Agility Venture Partners', 'Hindustan Media Venture',
       'Omnivore', 'Awign Enterprises',
       'Siddharth Bhaskar Shah, Upsparks', 'S Chand',
       'Goldman Sachs, Tata Capital', 'growX ventures, Venture Gurukool',
       'Mount Judi India Growth Fund', 'GEF Capital’s South Asia Fund',
       'Sunil Sethia, Sunil Kumar Singhvi, Manish Mardia',
       'Sequoia Capital', 'Mechanism Capital, DACM',
       'Northern Arc Capital, Niyogin Fintech Limited, Credit Saison India, Vivriti Capital',
       'Pearl Investment LLC', '021 Capital, Sparrow Capital',
       'Kotak Investment Advisors Limited, Gruhas Proptech', 'VANS Group',
       'Sachin Tendulkar', 'Xentel Investments', 'Accel Partners',
       'Waterbridge, Lumikai', 'Auxano, Falcon5', 'Infoedge ventures',
       'JITO Angel Network', 'Jupiter', 'Unitus Ventures',
       'GIC, Infoedge', 'pi Ventures',
       'Northern Arc, Caspian Impact Investments', 'Sofina Ventures SA',
       'Tiger Global, Flipkart Ventures',
       'Inflection Point Ventures, Rockstud Capital, Pentathlon Ventures, Prophetic Ventures syndicate',
       'Prime VP', 'Tribe Capital, IFC Emerging Asia Fund, VEF',
       'Sequoia’s Surge, Y Combinator', 'Endiya Partners',
       'Gokul Rajaram, Pureland Venture, Wavemaker Partners',
       'Callapina Capital', 'Khosla Ventures',
       'Accel Partners, Matrix India',
       'Omidyar Network India, Innoven Capital', 'Temasek, Falcon Edge',
       'Deep Kalra, Ashish Kashyap, Rajesh Magow',
       'IAN, Social Alpha, Startup Oasis', 'Capital India',
       'FirstCry, Lightspeed Venture Partners',
       'Accel, LetsVenture, 1Crowd', 'SAB Holdings',
       'Lightspeed Venture Partners, Elevation Capital',
       'Mumbai Angels Network', 'Jayanti Kanani',
       'LeapFrog, Khosla Ventures', 'Ananta Capital',
       'Northern Arc, Vivriti Capital', 'TATA Cleantech Capital',
       'Aqua-Spark', 'Climate Angels Fund',
       'Sequoia’s Surge, Nexus Venture Partners',
       'Entrepreneur First (EF), GrowX Ventures', 'Zephyr Peacock',
       'ADM Capital', 'SoftBank Vision Fund, Hindustan Media Venture',
       '100x Entrepreneurs', 'Healthcare veterans, PIEDS',
       'Bank of Baroda', 'YCombinator', 'IAN Fund', 'Vishal Gupta',
       'Mirae Asset, H&M', 'Kotak Securities', 'Klub',
       'Balaji Srinivasan', '$1000000', 'BASF Venture Capital GmbH',
       'Rebright Partners, Flourish Ventures', 'Sequoia Surge',
       'Titan Capital, Sequoia Capital', 'Parthiv Group',
       'Omkar Pandharkame, Ketaki Ogale',
       'GetVantage, Velocity, Shiprocket Capital', 'Krafton Inc, Omidyar',
       'Blume Ventures, Exfinity Venture Partners',
       'Beyond Next Ventures, M Venture Partners', 'AdvantEdge Founders',
       'Faering Capital, Sequoia Capital India, IIFL Alternate Asset Managers',
       'Sixth Sense Ventures, NABVENTURES', 'Temasek, Multiples PE',
       'Griffin Gaming Partners', 'Zinnia Global',
       'InfoEdge Ventures, IAN Fund', 'IIFL, Mumbai Angels',
       'BEENEXT, Sequoia’s Surge', 'Antler India', 'Bharat Inclusion',
       'Fidelity, BlackRock', 'Blacksoil', 'Speciale Invest',
       'Canbank Venture Capital Fund', 'W Health Ventures',
       '021 Capital, Y Combinator', 'Anand Prakash Sharma',
       'Axilor Ventures', 'velocity.in', 'March Capital, Tribe Capital',
       'Learn Capital', 'RTP Global', 'IAN, Yuj Ventures',
       'Sequoia’s Surge, Accel Partners', 'Uday Sodhi', 'Fidelity, GIC',
       'Auxano', 'Angelist India',
       'Stanford Angels and Entrepreneurs India, Anjali Bansal',
       'Vy Capital, Wellington Management', 'Avon Cycles',
       'Matrix Partners India, 021 Capital', 'HNIs, Angels',
       'NewQuest Capital Partners, Motilal Oswal Private Equity',
       'Lasons India', 'Pankaj Chaddah, Srivatsan Rajan', 'Paytm',
       'BlackSoil, CLSA Capital Partners', 'Saama, Whiteboard Capital',
       'Indian Angel Network, Titan Capital, Lead Angels',
       'The Chennai Angels',
       'Venture Highway, Stellaris Venture Partners',
       'State Bank of India, Y Combinator', 'Sanjay Baldwa, Ajay Jain',
       'InfoEdge', 'Nitin Passi, Ruchirans Jaipuria',
       'Stride Ventures, InnoVen Capital',
       'Venture Catalysts, Jeevak Gupta',
       'Triodos Investment Management, SAIF Partners', 'N+1 Capital',
       'DST Global, RTP Global', 'Amit Singal, Manish Aggarwal',
       'Trifecta Capital Advisors, Blume Ventures',
       'Kumar Aakash, Amit Singhal', 'growX ventures',
       'Shaival Desai, Alkemi Venture Partners',
       'Aavishkaar Venture Capital, YWC Venture Capital',
       'Alteria Capital', 'Tiga Investments, Baron Capital',
       'Venture Catalysts, 9unicorns', 'Qualgro',
       'Amit Lakhotia, Pravin Jadhav', 'Pravega Ventures',
       'Greenoaks Capital, Elevation Capital',
       'Sequoia Capital India, rocketship.vc', 'BLinC Invest',
       'Spring Marketing Capital', 'Chaitanya Kalipatnapu, Kedar Gavane',
       'Roha Investment Managers, angel investor Saumil Shah',
       'TNF Ventures, Razorpay', 'Lok Capital, IIFL Asset Management',
       'Nvidia Inception', 'Tiger Global Management, DST Global',
       'Marquee investors', 'Ashish Hemrajani, Parikshit Dar',
       'India Accelerator, Lyxel&Flamingo', 'Roshan Abbas, Ritesh Malik',
       'Goat Capital, JAM Fund', 'General Catalyst, Jungle Ventures',
       'Blackstone Group, ADQ', 'GoAhead Ventures',
       'Paradigm Shift Capital, AngelList India', 'Arali Ventures',
       'Anup Kumar Yama', 'Aryaman Vir', 'iSeed, Titan Capital',
       'Research Innovation Incubation Design Labs', 'Sushil Agarwal',
       'IvyCap Ventures, Endiya Partners',
       'GUSEC Seed Fund, DeVX Venture Fund', 'Tiger Global, Sequoia',
       'Quadria Capital', 'Blume Ventures, Whiteboard Capital',
       'Ashwini Kakkar. 9Unicorns', 'Ashish Shah', 'Faad Network',
       'Paragon Partners, Aavishkaar Capital', 'Krafton, Lumikai',
       'Indovation Fund, Mumbai Angels', 'Gunosy, Blume Ventures',
       'Edge Ventures, Elevation Capital', 'CDC Group',
       'Titan Capital, Kunal Shah',
       'Yamaha Motors, Omidyar Network India, Eight Roads Ventures',
       'Norfund, The Rise Fund', 'Siti Cable',
       'Crossbeam Venture Partners', 'Aavishkaar Capital', 'Mapmyindia',
       'Jyoti Bansal', 'Accor',
       'SRI Capital, Picus Capital, Alkemi Capital',

In [26]:
# Replacing the 'missing' values with Keyword "Unknown"

startup_2021['Investor'] = startup_2021['Investor'].apply(str)

#for i in range(investors_2021):
    #if investors_2021[i] == True:
        #startup_2021.Investor[i] = "unknown"

In [27]:
startup_2021.isna().sum()

Company/Brand      0
Founded            0
HeadQuarter        0
Sector             0
What it does       0
Founders           0
Investor           0
Amount($)          3
Stage            428
dtype: int64

### CLEANING OF THE AMOUNT COLUMN

In [28]:
startup_2021['Amount($)'].isna().sum()

3

In [29]:
startup_2021['Amount($)'].unique()

array(['$1,200,000', '$120,000,000', '$30,000,000', '$51,000,000',
       '$2,000,000', '$188,000,000', '$200,000', 'Undisclosed',
       '$1,000,000', '$3,000,000', '$100,000', '$700,000', '$9,000,000',
       '$40,000,000', '$49,000,000', '$400,000', '$300,000',
       '$25,000,000', '$160,000,000', '$150,000', '$1,800,000',
       '$5,000,000', '$850,000', '$53,000,000', '$500,000', '$1,100,000',
       '$6,000,000', '$800,000', '$10,000,000', '$21,000,000',
       '$7,500,000', '$26,000,000', '$7,400,000', '$1,500,000',
       '$600,000', '$800,000,000', '$17,000,000', '$3,500,000',
       '$15,000,000', '$215,000,000', '$2,500,000', '$350,000,000',
       '$5,500,000', '$83,000,000', '$110,000,000', '$500,000,000',
       '$65,000,000', '$150,000,000,000', '$300,000,000', '$2,200,000',
       '$35,000,000', '$140,000,000', '$4,000,000', '$13,000,000', nan,
       '$Undisclosed', '$2000000', '$800000', '$6000000', '$2500000',
       '$9500000', '$13000000', '$5000000', '$8000000', '$1000000',
       'Upsparks', '$200000', '$12000000', '$1500000', '$1700000',
       '$5500000', '$400000', '$150000000', '$4000000', '$100000000',
       '$500000', '$15000000', '$10000000', '$40000000', '$225000000',
       '$6700000', '$1300000', '$20000000', '$250000', '$21000000',
       '$1200000', '$52000000', '$3800000', '$17500000', '$42000000',
       '$2300000', '$7000000', '$30000000', '$450000000', '$28000000',
       '$300000', '$3500000', '$8500000', '$25000000', '$3000000',
       '$37000000', '$370000000', '$700000', '$16000000', '$100000',
       '$44000000', '$770000', '$125000000', '$35000000', '$50000000',
       '$4900000', '$145000000', '$22000000', '$70000000', '$6600000',
       '$32000000', '$24000000', '$725000', '$461000', 'Series C', 'Seed',
       '$96000000', '$60000000', '$500000000', '$266000000', '$4500000',
       '$325000000', '$6500000', '$1600000', '$225000', '$85000000',
       '$235000', '$260000', '$2900000', '$53000000', '$1100000',
       '$150000', '$86000000', '$130000', '$$100,00', '$111000000',
       '$265000', '$76000000', '$100,000,000', '$75,000,000',
       '$3,800,000', '$12,000,000', '$1,600,000', '$260,000',
       '$1,000,000,000', '$18,000,000', '$20,000,000', '$350,000',
       '$95,000,000', '$4,100,000', '$5,200,000', '$8,000,000',
       '$1,400,000', '$2,600,000', '$900,000', '$250,000', '$16,000,000',
       '$7,000,000', '$11,000,000', '$50,000,000', '$14,300,000',
       '$81,000,000', '$1,300,000', '$8,200,000', '$280,000,000',
       '$70,000,000', '$720,000', '$600000', '$9000000', '$1800000',
       '$330000', '$undisclosed', '$200000000', '$36000000', '$67000000',
       '$10200000', '$220000000', '$108000000', '$75000000', '$450000',
       '$660000000', 'ah! Ventures', '$45000000', '$3200000', '$370000',
       'Pre-series A', 'ITO Angel Network, LetsVenture', '$48000000',
       '$3600000', '$11000000', '$192000000', '$65000000', '$1400000',
       '$1900000', '$41000000', '$144000000', '$5200000', '$270000000',
       '$140000', '$250000000', '$320000', '$350000000', '$4800000',
       '$38000000', '$125000', '$26000000', '$64000000', '$620000',
       '$900000', 'JITO Angel Network, LetsVenture', '$2600000',
       '$1,250,000', '$400,000,000', '$1,700,000', '$27,000,000',
       '$234,000,000', '$460,000,000', '$13,500,000', '$5,100,000',
       '$195,000,000', '$125,000', '$45,000,000', '$200,000,000',
       '$7,300,000', '$6,300,000', '$12,500,000', '$24,000,000',
       '$140,000', '$16,500,000', '$340,000', '$43,000,000',
       '$150,000,000', '$3300000', '$92000000', '$17000000', '$135000000',
       '$$1,55,000', '$2100000', '$840000000', '$248000000', '$4300000',
       '$570000', '$2200000', '$4700000', '$300000000', '$260000000',
       '$140000000', '$175000000', '$19000000', '$810000', '$7500000',
       '$600000000', '$90000000', '$5700000', '$6750000', '$78000000',
       '$5400000', '$115000000', '$255000000', '$18000000', '$570000000',
       '$550000', '$2700000', '$4200000', '$31000000', '$540000',
       '$14000000', '$340000', '$', '$6200000', '$750000', '$6300000',
       '$23000000', '$55000000'], dtype=object)

In [31]:
# converting the datatype to string

startup_2021['Amount($)'] = startup_2021['Amount($)'].apply(str)


# Removing the comas and spaces

startup_2021['Amount($)'].replace(',','', inplace = True, regex = True)

startup_2021

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage
0,Unbox Robotics,2019,Bangalore,AI startup,Unbox Robotics builds on-demand AI-driven ware...,"Pramod Ghadge, Shahid Memon","BEENEXT, Entrepreneur First",$1200000,Pre-series A
1,upGrad,2015,Mumbai,EdTech,UpGrad is an online higher education platform.,"Mayank Kumar, Phalgun Kompalli, Ravijot Chugh,...","Unilazer Ventures, IIFL Asset Management",$120000000,NaN
2,Lead School,2012,Mumbai,EdTech,LEAD School offers technology based school tra...,"Smita Deorah, Sumeet Mehta","GSV Ventures, Westbridge Capital",$30000000,Series D
3,Bizongo,2015,Mumbai,B2B E-commerce,Bizongo is a business-to-business online marke...,"Aniket Deb, Ankit Tomar, Sachin Agrawal","CDC Group, IDG Capital",$51000000,Series C
4,FypMoney,2021,Gurugram,FinTech,"FypMoney is Digital NEO Bank for Teenagers, em...",Kapil Banwari,"Liberatha Kallat, Mukesh Yadav, Dinesh Nagpal",$2000000,Seed
...,...,...,...,...,...,...,...,...,...
1204,Gigforce,2019,Gurugram,Staffing & Recruiting,A gig/on-demand staffing company.,"Chirag Mittal, Anirudh Syal",Endiya Partners,$3000000,Pre-series A
1205,Vahdam,2015,New Delhi,Food & Beverages,VAHDAM is among the world’s first vertically i...,Bala Sarda,IIFL AMC,$20000000,Series D
1206,Leap Finance,2019,Bangalore,Financial Services,International education loans for high potenti...,"Arnav Kumar, Vaibhav Singh",Owl Ventures,$55000000,Series C
1207,CollegeDekho,2015,Gurugram,EdTech,"Collegedekho.com is Student’s Partner, Friend ...",Ruchir Arora,"Winter Capital, ETS, Man Capital",$26000000,Series B
1208,WeRize,2019,Bangalore,Financial Services,India’s first socially distributed full stack ...,"Vishal Chopra, Himanshu Gupta","3one4 Capital, Kalaari Capital",$8000000,Series A

In [32]:
startup_2021['Amount($)'].unique()

array(['$1200000', '$120000000', '$30000000', '$51000000', '$2000000',
       '$188000000', '$200000', 'Undisclosed', '$1000000', '$3000000',
       '$100000', '$700000', '$9000000', '$40000000', '$49000000',
       '$400000', '$300000', '$25000000', '$160000000', '$150000',
       '$1800000', '$5000000', '$850000', '$53000000', '$500000',
       '$1100000', '$6000000', '$800000', '$10000000', '$21000000',
       '$7500000', '$26000000', '$7400000', '$1500000', '$600000',
       '$800000000', '$17000000', '$3500000', '$15000000', '$215000000',
       '$2500000', '$350000000', '$5500000', '$83000000', '$110000000',
       '$500000000', '$65000000', '$150000000000', '$300000000',
       '$2200000', '$35000000', '$140000000', '$4000000', '$13000000',
       'nan', '$Undisclosed', '$9500000', '$8000000', 'Upsparks',
       '$12000000', '$1700000', '$150000000', '$100000000', '$225000000',
       '$6700000', '$1300000', '$20000000', '$250000', '$52000000',
       '$3800000', '$17500000', '$42000000', '$2300000', '$7000000',
       '$450000000', '$28000000', '$8500000', '$37000000', '$370000000',
       '$16000000', '$44000000', '$770000', '$125000000', '$50000000',
       '$4900000', '$145000000', '$22000000', '$70000000', '$6600000',
       '$32000000', '$24000000', '$725000', '$461000', 'Series C', 'Seed',
       '$96000000', '$60000000', '$266000000', '$4500000', '$325000000',
       '$6500000', '$1600000', '$225000', '$85000000', '$235000',
       '$260000', '$2900000', '$86000000', '$130000', '$$10000',
       '$111000000', '$265000', '$76000000', '$75000000', '$1000000000',
       '$18000000', '$350000', '$95000000', '$4100000', '$5200000',
       '$1400000', '$2600000', '$900000', '$11000000', '$14300000',
       '$81000000', '$8200000', '$280000000', '$720000', '$330000',
       '$undisclosed', '$200000000', '$36000000', '$67000000',
       '$10200000', '$220000000', '$108000000', '$450000', '$660000000',
       'ah! Ventures', '$45000000', '$3200000', '$370000', 'Pre-series A',
       'ITO Angel Network LetsVenture', '$48000000', '$3600000',
       '$192000000', '$1900000', '$41000000', '$144000000', '$270000000',
       '$140000', '$250000000', '$320000', '$4800000', '$38000000',
       '$125000', '$64000000', '$620000',
       'JITO Angel Network LetsVenture', '$1250000', '$400000000',
       '$27000000', '$234000000', '$460000000', '$13500000', '$5100000',
       '$195000000', '$7300000', '$6300000', '$12500000', '$16500000',
       '$340000', '$43000000', '$3300000', '$92000000', '$135000000',
       '$$155000', '$2100000', '$840000000', '$248000000', '$4300000',
       '$570000', '$4700000', '$260000000', '$175000000', '$19000000',
       '$810000', '$600000000', '$90000000', '$5700000', '$6750000',
       '$78000000', '$5400000', '$115000000', '$255000000', '$570000000',
       '$550000', '$2700000', '$4200000', '$31000000', '$540000',
       '$14000000', '$', '$6200000', '$750000', '$23000000', '$55000000'],
      dtype=object)

In [33]:

startup_2021['Amount($)'] = startup_2021['Amount($)'].replace('Undisclosed','np.nan', regex = True)

startup_2021['Amount($)'] = startup_2021['Amount($)'].replace('$undisclosed','np.nan', regex = True)

startup_2021['Amount($)'] = startup_2021['Amount($)'].replace('$Undisclosed','np.nan', regex = True)

startup_2021['Amount($)'] = startup_2021['Amount($)'].replace('nan','np.nan', regex = True)

startup_2021['Amount($)'] = startup_2021['Amount($)'].replace('Undislosed','np.nan', regex = True)

In [34]:
startup_2021['Amount($)'].unique()

array(['$1200000', '$120000000', '$30000000', '$51000000', '$2000000',
       '$188000000', '$200000', 'np.np.nan', '$1000000', '$3000000',
       '$100000', '$700000', '$9000000', '$40000000', '$49000000',
       '$400000', '$300000', '$25000000', '$160000000', '$150000',
       '$1800000', '$5000000', '$850000', '$53000000', '$500000',
       '$1100000', '$6000000', '$800000', '$10000000', '$21000000',
       '$7500000', '$26000000', '$7400000', '$1500000', '$600000',
       '$800000000', '$17000000', '$3500000', '$15000000', '$215000000',
       '$2500000', '$350000000', '$5500000', '$83000000', '$110000000',
       '$500000000', '$65000000', '$150000000000', '$300000000',
       '$2200000', '$35000000', '$140000000', '$4000000', '$13000000',
       'np.nan', '$np.np.nan', '$9500000', '$8000000', 'Upsparks',
       '$12000000', '$1700000', '$150000000', '$100000000', '$225000000',
       '$6700000', '$1300000', '$20000000', '$250000', '$52000000',
       '$3800000', '$17500000', '$42000000', '$2300000', '$7000000',
       '$450000000', '$28000000', '$8500000', '$37000000', '$370000000',
       '$16000000', '$44000000', '$770000', '$125000000', '$50000000',
       '$4900000', '$145000000', '$22000000', '$70000000', '$6600000',
       '$32000000', '$24000000', '$725000', '$461000', 'Series C', 'Seed',
       '$96000000', '$60000000', '$266000000', '$4500000', '$325000000',
       '$6500000', '$1600000', '$225000', '$85000000', '$235000',
       '$260000', '$2900000', '$86000000', '$130000', '$$10000',
       '$111000000', '$265000', '$76000000', '$75000000', '$1000000000',
       '$18000000', '$350000', '$95000000', '$4100000', '$5200000',
       '$1400000', '$2600000', '$900000', '$11000000', '$14300000',
       '$81000000', '$8200000', '$280000000', '$720000', '$330000',
       '$undisclosed', '$200000000', '$36000000', '$67000000',
       '$10200000', '$220000000', '$108000000', '$450000', '$660000000',
       'ah! Ventures', '$45000000', '$3200000', '$370000', 'Pre-series A',
       'ITO Angel Network LetsVenture', '$48000000', '$3600000',
       '$192000000', '$1900000', '$41000000', '$144000000', '$270000000',
       '$140000', '$250000000', '$320000', '$4800000', '$38000000',
       '$125000', '$64000000', '$620000',
       'JITO Angel Network LetsVenture', '$1250000', '$400000000',
       '$27000000', '$234000000', '$460000000', '$13500000', '$5100000',
       '$195000000', '$7300000', '$6300000', '$12500000', '$16500000',
       '$340000', '$43000000', '$3300000', '$92000000', '$135000000',
       '$$155000', '$2100000', '$840000000', '$248000000', '$4300000',
       '$570000', '$4700000', '$260000000', '$175000000', '$19000000',
       '$810000', '$600000000', '$90000000', '$5700000', '$6750000',
       '$78000000', '$5400000', '$115000000', '$255000000', '$570000000',
       '$550000', '$2700000', '$4200000', '$31000000', '$540000',
       '$14000000', '$', '$6200000', '$750000', '$23000000', '$55000000'],
      dtype=object)

In [35]:
startup_2021['Amount($)']

0       False
1       False
2       False
3       False
4       False
        ...
1204     True
1205     True
1206    False
1207     True
1208     True
Name: Amount($), Length: 1209, dtype: bool

# MANUAL CHECKING AND REARRANGING MISS PLACED COLUMNS

In [40]:
startup_2021[:100]

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage
0,Unbox Robotics,2019,Bangalore,AI startup,Unbox Robotics builds on-demand AI-driven ware...,"Pramod Ghadge, Shahid Memon","BEENEXT, Entrepreneur First",$1200000,Pre-series A
1,upGrad,2015,Mumbai,EdTech,UpGrad is an online higher education platform.,"Mayank Kumar, Phalgun Kompalli, Ravijot Chugh,...","Unilazer Ventures, IIFL Asset Management",$120000000,NaN
2,Lead School,2012,Mumbai,EdTech,LEAD School offers technology based school tra...,"Smita Deorah, Sumeet Mehta","GSV Ventures, Westbridge Capital",$30000000,Series D
3,Bizongo,2015,Mumbai,B2B E-commerce,Bizongo is a business-to-business online marke...,"Aniket Deb, Ankit Tomar, Sachin Agrawal","CDC Group, IDG Capital",$51000000,Series C
4,FypMoney,2021,Gurugram,FinTech,"FypMoney is Digital NEO Bank for Teenagers, em...",Kapil Banwari,"Liberatha Kallat, Mukesh Yadav, Dinesh Nagpal",$2000000,Seed
...,...,...,...,...,...,...,...,...,...
95,TartanSense,2015,Bangalore,Information Technology,TartanSense unlocks value for small farm holde...,Jaisimha Rao,"FMC, Omnivore, Blume Ventures",$5000000,NaN
96,Bewakoof,2012,Mumbai,Apparel & Fashion,Bewakoof is a lifestyle fashion brand that mak...,Prabhkiran Singh,InvestCorp,$8000000,NaN
97,Kirana247,2018,New Delhi,Logistics & Supply Chain,An on-demand FMCG supply chain company leverag...,"Tarun Jiwarajka, Pankhuri Jiwarajka",nan,$1000000,NaN
98,FanPlay,2020,Computer Games,Computer Games,A real money game app specializing in trivia g...,YC W21,"Pritesh Kumar, Bharat Gupta",Upsparks,$1200000
99,NeoDocs,2020,Mumbai,Healthtech,Neodocs is a part of India's prominent Social ...,"Nikunj Malpani, Anurag Meena, Pratik Lodha","Y Combinator, 9Unicorns, Titan Capital",$np.np.nan,NaN

In [43]:
# There is a missed placed value in index 98 = FanPlay, the Amount Column is interchanged with the Stage Column

startup_2021.loc[startup_2021['Company/Brand'] == 'FanPlay']

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage
98,FanPlay,2020,Computer Games,Computer Games,A real money game app specializing in trivia g...,YC W21,"Pritesh Kumar, Bharat Gupta",Upsparks,$1200000
111,FanPlay,2020,Computer Games,Computer Games,A real money game app specializing in trivia g...,YC W21,"Pritesh Kumar, Bharat Gupta",Upsparks,$1200000

### From the above, it is obvious that FanPlay has a duplicated row and Amount Column interchanged with the Stage column

In [51]:
# Dropping the duplicated row

startup_2021.drop([98],axis=0,inplace=True)

In [52]:
startup_2021.loc[startup_2021['Company/Brand'] == 'FanPlay']

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage
111,FanPlay,2020,Computer Games,Computer Games,A real money game app specializing in trivia g...,YC W21,"Pritesh Kumar, Bharat Gupta",Upsparks,$1200000

In [53]:
# Correcting the miss placed values ie interchanging the amount value with the Stage value

startup_2021.loc[startup_2021['Company/Brand'] == 'FanPlay',['Amount($)','Stage','Investor',]] = [1200000,'Series A','Upsparks']

In [54]:
# viewing the correction result

startup_2021.loc[startup_2021['Company/Brand'] == 'FanPlay']

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage
111,FanPlay,2020,Computer Games,Computer Games,A real money game app specializing in trivia g...,YC W21,Upsparks,1200000,Series A

In [58]:
startup_2021[250:300]

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage
251,Enmovil,2015,Hyderabad,Information Technology & Services,Enmovil delivers a Business Intelligence Platf...,"Ravi Bulusu, Nanda Kishore, Venkat Moganty",Anicut Angel Fund,$1300000,Pre-series A
252,ASQI Advisors,2019,Mumbai,Financial Services,Bringing Blockchain technology intro mainstrea...,Swapnil Pawar,Founders Room Capital,$1000000,Pre-series A
253,Insurance Samadhan,2018,New Delhi,Insurance,The insurance industry will help in representa...,Deepak Bhuvenshwari Uniyal,"9Unicorns, ZNL",$725000,Pre-series A
254,Evenflow Brands,2020,Mumbai,Consumer Goods,Identify and partner with the upcoming eCommer...,"Utsav Agarwal, Pulkit Chhabra",nan,$500000,NaN
255,MasterChow,2020,Food & Beverages,Hauz Khas,A ready-to-cook Asian cuisine brand,"Vidur Kataria, Sidhanth Madan",WEH Ventures,$461000,Seed
256,Fullife Healthcare,2009,Pharmaceuticals,Primary Business is Development and Manufactur...,Varun Khanna,Morgan Stanley Private Equity Asia,$22000000,Series C,NaN
257,MoEVing,2021,Gurugram,MoEVing is India's only Electric Mobility focu...,"Vikash Mishra, Mragank Jain","Anshuman Maheshwary, Dr Srihari Raju Kalidindi",$5000000,Seed,NaN
258,Pristyn Care,2018,Gurugram,Hospital & Health Care,A new age health tech company that aims to sim...,"Harsimarbir (Harsh) Singh, Dr Vaibhav Kapoor, ...","Kunal Shah, Deepinder Goyal, Abhiraj Singh Bhal",$96000000,Series E
259,Plix,2018,Mumbai,"Health, Wellness & Fitness",Plant-based nutraceutical firm,"Rishubh Satiya, Akash Zaveri","Guild Capital, RPSG Capital Ventures",$5000000,Series A
260,Uni Cards,2020,Bangalore,Financial Services,"Uni Card splits your payments into 3 parts, ov...","Nitin Gupta, Prateek Jindal, Laxmikant Vyas","General Catalyst, Eight Roads Ventures, Elevat...",$70000000,Series A
261,Practically,2018,Hyderabad,E-learning,An experiential learning app for grades 6th to...,"Subbarao Siddabattula, Charu Noheria, Ilangove...","NB Ventures, Earlsfield Capital",$5000000,NaN
262,Nestasia,2018,Kolkata,Retail,"Artisanal, Handmade, bio conscious crafts from...","Aditi Murarka Agrawal, Anurag Agrawal","Varun Alagh, Sahil Barua",$4000000,Series A
263,Vedic Cosmeceuticals,2002,Noida,Cosmetics,One of india’s most trusted and technologicall...,Mohit Goel,Sixth Sense Ventures,$32000000,Series A
264,Juspay,2012,Bangalore,FinTech,Enable frictionless payments for the billion I...,"Vimal Kumar, Ramanathan RV",SoftBank Vision Fund 2,$60000000,Series C
265,TranZact,2017,Mumbai,Information Technology & Services,A mission to digitize millions of Indian SMEs ...,"Ritesh Kumar, Sharad Sen Sharma, Rohan Sen Sharma","Tribe Capital, Prime Venture Partners",$7000000,Series A
266,Atomberg,2012,Mumbai,Consumer Electronics,Atomberg has built the ‘Brushless DC Motor’ (B...,"Manoj, Sibabrata Das",Jungle Ventures,$20000000,NaN
267,Ola,2010,Bangalore,Mobility,Ola is India’s largest mobility platform and o...,Bhavish Aggarwal,Marquee international institutional investors,$500000000,NaN
268,Mohalla Tech,2015,Bangalore,Social media,Mohalla Tech Pvt. Ltd. is a computer software ...,"Ankush Sachdeva, Bhanu Pratap Singh",Alkeon Capital,$266000000,Series G
269,Stack,2020,Bangalore,Financial Services,Stack is an investing platform set to put mone...,"Smriti Tomar, Tushar Vyas","Y Combinator, Harvard Management",$4500000,Seed
270,PropReturns,2020,Mumbai,Real Estate,PropReturns is a platform for users to invest ...,"Jayant Panwar, Kenish Shah","Y Combinator﻿, ﻿Goodwater Capital",$1200000,NaN
271,WeSkill,2020,Gurugram,E-learning,Act as the bridge for skills providing access ...,"Shaurya Joshi, Shashank Patidar, Praneet Agarwal","Shrishti Sahu, Umang Vohra",$4000000,Pre-seed
272,Fitpage,2020,Mumbai,"Health, Wellness & Fitness",An endurance-first fitness tech platform focus...,Vikas Singh,"Astra Ventures, Gaurav Jaitly",$300000,NaN
273,ShopMyLooks,2021,Noida,Digital platform,ShopMyLooks turns social media photos & videos...,Rohit Jaiswal,"Capital A, Collective Artists Network",$200000,NaN
274,ByteLearn,2021,Noida,E-learning,AI powered teaching assistant for 100 Mn teach...,Undefined,"Aditya Singhal, Nishant Sinha",$9500000,Seed
275,Dista,2017,Pune,Computer Software,Dista is an AI-enabled location intelligence p...,"Nishant Kumar, Shishir Gokhale, Deepak Garg",Pentathlon Ventures,$1200000,Seed
276,OfBusiness,2015,Gurugram,Financial Services,OfBusiness is a new age commerce and fintech s...,"Ruchi Kalra, Asish Mohapatra","Alpha Wave Ventures II, Tiger Global Managemen...",$325000000,NaN
277,Bizongo,2015,Mumbai,B2B Ecommerce,izongo is India’s largest B2B platform for mad...,"Sachin Agrawal, Aniket Deb, Ankit Tomar",Tiger Global,$100000000,Series D
278,FRND,2019,Bangalore,Online Media,FRND is an audio dating app for Bharat,"Bhanu Pratap Singh Tanwar, Hardik Bansal, Hars...",KRAFTON,$6500000,Series A
279,Metadome,2017,Bangalore,Computer Software,"Metadome (formerly Adloid), is a Metaverse, th...","Kanav Singla, Prashant Sinha, Shorya Mahajan","Chiratae Ventures, Lenskart Vision Fund",$4000000,Pre-series A
280,Keka HR,2014,Hyderabad,Information Technology & Services,Keka is a simple and intuitive HR software unl...,Vijay Yalamanchili,Recur Club,$1600000,NaN
281,Flo Mobility,2019,Bangalore,Industrial Automation,An autonomous tech stack that can be applied t...,"Manesh Jain, Mohan Kumar","DevX Venture Fund, Blume Founder Fund",$400000,NaN
282,Yodacart,2019,Thane,E-commerce,YODACART is an e-commerce startup offering rea...,Vikas Sharma,Ajith Daneil,$225000,Pre-seed
283,TheHouseMonk,2019,Bangalore,Real Estate,A complete property management software platfo...,"Ajay Kumar, Balaji Varadharajan",Aurum Proptech,$5000000,NaN
284,Zepto,2021,Bangalore,E-commerce,"Ability to consistently deliver 2,500+ product...","Aadit Palicha, Kaivalya Vohra",Y-Combinator,$100000000,NaN
285,Sirona Hygiene,2015,New Delhi,"Health, Wellness & Fitness","An award-winning brand, committed to solving t...",Deep Bajaj,The Good Glamm Group,$10000000,NaN
286,Jumbotail,2015,Bangalore,B2B Ecommerce,Jumbotail is India's leading B2B marketplace a...,"S Karthik Venkateswaran, Ashish Jhina",Invus,$85000000,Series C
287,Captain Fresh,2019,Bangalore,Logistics & Supply Chain,A B2B marketplace leveraging technology to del...,Utham Gowda,"Tiger Global, Prosus Ventures",$40000000,Series B
288,Deciwood,2018,New Delhi,Consumer Electronics,Deciwood makes Eco-friendly wooden speakers us...,Ananya Meena,"Shuru Up, Ankit Kedia, Arun Gupta",$200000,NaN
289,Kohbee,2019,Bangalore,E-learning,Kohbee is a mobile app for online trainers and...,"Rohan Sinha, Shashwat Aditya","Ankit Mehrotra, Saurabh Aggarwal",$235000,Pre-seed
290,Perfora,2021,Gurugram,Consumer Goods,"Building a disruptive, modern, and functional ...","Tushar Khurana, Jatan Bawa",Sauce.vc,$260000,Pre-seed
291,Unbox Robotics,2019,Pune,Logistics & Supply Chain,Unbox Robotics is building software-defined ro...,"Pramod Ghadge, Shahid Memon, Rohit Pitale","3one4 Capital, Sixth Sense Ventures",$7000000,Series A
292,Ninety One,2015,Ahmedabad,Consumer Goods,"Ninety One makes cycles, which the company cla...","Sachin Chopra, Vishal Chopra",A91 Partners,$30000000,Series A
293,Gobillion,2020,New Delhi,Social commerce,Redefining social commerce for Tier 2+ cities ...,"Roshan Farhan, Kulapradip Bharali","YCombinator, Justin Mateen, Pioneer Fund",$2900000,Seed
294,RIPPLR,2019,Bangalore,Logistics & Supply Chain,India’s first Plug-n-Play distribution ecosyst...,"Abhishek Nehru, Santosh Dabke","Sojitz Corporation, Stride Ventures",$12000000,Pre-series B
295,SK Finance,1994,Jaipur,Financial Services,SK Finance is a leading player in vehicle fina...,Rajendra Setia,"IIFL Wealth, TPG Growth, Norwest Venture Partners",$53000000,Series F
296,Eggoz,2017,Gurugram,Food & Beverages,Make a meaningful impact to improve the protei...,"Abhishek Negi, Uttam Kumar, Aditya Singh, Pank...","Nabventures, Avaana Capital",$3500000,Series A
297,Fabriclore,2016,Jaipur,Apparel & Fashion,India's top brand of artisanal & contemporary ...,"Vijay Sharma, Anupam Arya, Sandeep Sharma","Fluid Ventures, Mulberry Silks",$700000,Pre-series A
298,Veefin,2010,Mumbai,Information Technology & Services,Veefin is the world leader in contextual SCF a...,"Gautam Udani, Raja Debnath",Rajesh Rajendran,$3000000,NaN
299,Verandah,2011,Mumbai,Apparel & Fashion,Verandah is a conscious luxury travel brand re...,Anjali Patel Mehta,"Mike Novogratz, Neeraj Arora",$1000000,Seed
300,Karkinos Healthcare,2020,Mumbai,Hospital & Health Care,Medical center for treatment of complex cancer...,"R Venkataramanan, Ravi Kant",Reliance Digital Health,$np.np.nan,NaN

In [59]:
# At index 256 and 257, there are miss placed columns in Investor, Amount, Stage, headquarter, Company/Brand

# VIEWING INDEX 256

startup_2021.loc[startup_2021['Company/Brand'] == 'Fullife Healthcare']

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage
242,Fullife Healthcare,2009,Pharmaceuticals,Primary Business is Development and Manufactur...,Varun Khanna,Morgan Stanley Private Equity Asia,$22000000,Series C,NaN
256,Fullife Healthcare,2009,Pharmaceuticals,Primary Business is Development and Manufactur...,Varun Khanna,Morgan Stanley Private Equity Asia,$22000000,Series C,NaN

In [60]:
# Fullife Healthcare has duplicate, so we remove the duplicate row

startup_2021.drop([242],axis=0,inplace=True)

In [61]:
startup_2021.loc[startup_2021['Company/Brand'] == 'Fullife Healthcare']

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage
256,Fullife Healthcare,2009,Pharmaceuticals,Primary Business is Development and Manufactur...,Varun Khanna,Morgan Stanley Private Equity Asia,$22000000,Series C,NaN

In [74]:
# CORRECTING THE MISS PLACED VALUES

startup_2021.loc[startup_2021['Company/Brand'] == 'Fullife Healthcare',['Amount($)','Stage','Investor',
    'Founders','What it does','Sector','HeadQuarter']] = [22000000,'Series C','Morgan Stanley Private Equity Asia','Varun Khanna',
    'Primary Business is Development and Manufactur...','Pharmaceuticals','Mumbai']

In [75]:
# VIEWING THE CORRECTIONS

startup_2021.loc[startup_2021['Company/Brand'] == 'Fullife Healthcare']

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage
256,Fullife Healthcare,2009,Mumbai,Pharmaceuticals,Primary Business is Development and Manufactur...,Varun Khanna,Morgan Stanley Private Equity Asia,22000000,Series C

In [65]:
# TREATING INDEX 257

startup_2021.loc[startup_2021['Company/Brand'] == 'MoEVing']

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage
257,MoEVing,2021,Gurugram,MoEVing is India's only Electric Mobility focu...,"Vikash Mishra, Mragank Jain","Anshuman Maheshwary, Dr Srihari Raju Kalidindi",$5000000,Seed,NaN

In [72]:
# DEALING WITH ERROR AT INDEX 257

startup_2021.loc[startup_2021['Company/Brand'] == 'MoEVing',['Amount($)','Stage','Investor','Sector',
    'What it does','Founders']] = [5000000,'Seed','Anshuman Maheshwary, Dr Srihari Raju Kalidindi','Power',
    'MoEVing is Indian only Electric Mobility focu...','Vikash Mishra, Mragank Jain']

In [73]:
# VIEWING THE CORRECTION

startup_2021.loc[startup_2021['Company/Brand'] == 'MoEVing']

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage
257,MoEVing,2021,Gurugram,Power,MoEVing is Indian only Electric Mobility focu...,"Vikash Mishra, Mragank Jain","Anshuman Maheshwary, Dr Srihari Raju Kalidindi",5000000,Seed

In [69]:
# AT INDEX 538 THERE IS A MISS PLACED COLUMN

startup_2021.loc[startup_2021['Company/Brand'] == 'Little Leap']

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage
538,Little Leap,2020,New Delhi,EdTech,Soft Skills that make Smart Leaders,Holistic Development Programs for children in ...,Vishal Gupta,ah! Ventures,$300000

In [70]:
# CORRECTING THE MISS PLACED VALUES

startup_2021.loc[startup_2021['Company/Brand'] == 'Little Leap',['Amount($)','Stage','Investor',
    'Founders']] = [300000,'Seed','ah! Ventures','Vishal Gupta']

In [71]:
# VIEWING THE CORRECTION

startup_2021.loc[startup_2021['Company/Brand'] == 'Little Leap']

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage
538,Little Leap,2020,New Delhi,EdTech,Soft Skills that make Smart Leaders,Vishal Gupta,ah! Ventures,300000,Seed

In [76]:
# MISS PLACED COLUMN AT INDEX 551

startup_2021.loc[startup_2021['Company/Brand'] == 'BHyve']

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage
551,BHyve,2020,Mumbai,Human Resources,A Future of Work Platform for diffusing Employ...,Backed by 100x.VC,"Omkar Pandharkame, Ketaki Ogale",ITO Angel Network LetsVenture,$300000

In [77]:
# CORRECTING THE MISS PLACED VALUES

startup_2021.loc[startup_2021['Company/Brand'] == 'BHyve',['Amount($)','Stage','Founders','Investor']] = [300000,'np.nan',
 'Omkar Pandharkame, Ketaki Ogale','ITO Angel Network LetsVenture']

In [78]:
# VIEWING THE CORRECTION

startup_2021.loc[startup_2021['Company/Brand'] == 'BHyve']

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage
551,BHyve,2020,Mumbai,Human Resources,A Future of Work Platform for diffusing Employ...,"Omkar Pandharkame, Ketaki Ogale",ITO Angel Network LetsVenture,300000,np.nan

In [79]:
# MISS PLACED COLUMN AT INDEX 1148

startup_2021.loc[startup_2021['Company/Brand'] == 'Godamwale']

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage
1148,Godamwale,2016,Mumbai,Logistics & Supply Chain,Godamwale is tech enabled integrated logistics...,"Basant Kumar, Vivek Tiwari, Ranbir Nandan",1000000\t#REF!,Seed,NaN

In [80]:
# CORRECTING THE MISS PLACED VALUES

startup_2021.loc[startup_2021['Company/Brand'] == 'Godamwale',['Amount($)','Stage','Investor']] = [1000000,'Seed',
 'Unknown']

In [81]:

# VIEWING THE CORRECTION

startup_2021.loc[startup_2021['Company/Brand'] == 'Godamwale']

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage
1148,Godamwale,2016,Mumbai,Logistics & Supply Chain,Godamwale is tech enabled integrated logistics...,"Basant Kumar, Vivek Tiwari, Ranbir Nandan",Unknown,1000000,Seed

In [85]:
# MISS PLACED COLUMN AT INDEX 545

startup_2021.loc[startup_2021['Company/Brand'] == 'AdmitKard']

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage
545,AdmitKard,2016,Noida,EdTech,A tech solution for end to end career advisory...,"Vamsi Krishna, Pulkit Jain, Gaurav Munjal\t#REF!",$1000000,Pre-series A,NaN

In [104]:
# CORRECTING THE MISS PLACED VALUES

startup_2021.loc[startup_2021['Company/Brand'] == 'AdmitKard',['Amount($)','Stage','Investor','Founders']] = [1000000,'Pre-series A',
 'Unknown','Vamsi Krishna, Pulkit Jain, Gaurav Munjal']

In [105]:
# VIEWING THE CORRECTION


startup_2021.loc[startup_2021['Company/Brand'] == 'AdmitKard']

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage
545,AdmitKard,2016,Noida,EdTech,A tech solution for end to end career advisory...,"Vamsi Krishna, Pulkit Jain, Gaurav Munjal",Unknown,1000000,Pre-series A

In [107]:
# MISS PLACED COLUMNS AT INDEX 677

startup_2021.loc[startup_2021['Amount($)'] == 'JITO Angel Network LetsVenture']

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage
677,Saarthi Pedagogy,2015,Ahmadabad,EdTech,"India's fastest growing Pedagogy company, serv...",Pedagogy,Sushil Agarwal,JITO Angel Network LetsVenture,$1000000

In [109]:
# CORRECTING THE MISS PLACED VALUES

startup_2021.loc[startup_2021['Company/Brand'] == 'Saarthi Pedagogy',['Amount($)','Stage']] = [1000000,'Seed']

In [110]:
# VIEWING THE CORRECTION

startup_2021.loc[startup_2021['Company/Brand'] == 'Saarthi Pedagogy']

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage
677,Saarthi Pedagogy,2015,Ahmadabad,EdTech,"India's fastest growing Pedagogy company, serv...",Pedagogy,Sushil Agarwal,1000000,Seed

In [111]:
# REPLACING THE "NAN" VALUES WITH "0"

startup_2021['Amount($)'] = startup_2021['Amount($)'].replace('nan',0, regex = True)

In [114]:
# REPLACING THE DOLLAR SIGN WITH AN EMPTY STRING


startup_2021['Amount($)'] = startup_2021['Amount($)'].apply(lambda x: str(x).replace('$',''))

In [115]:
startup_2021

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage
0,Unbox Robotics,2019,Bangalore,AI startup,Unbox Robotics builds on-demand AI-driven ware...,"Pramod Ghadge, Shahid Memon","BEENEXT, Entrepreneur First",1200000,Pre-series A
1,upGrad,2015,Mumbai,EdTech,UpGrad is an online higher education platform.,"Mayank Kumar, Phalgun Kompalli, Ravijot Chugh,...","Unilazer Ventures, IIFL Asset Management",120000000,NaN
2,Lead School,2012,Mumbai,EdTech,LEAD School offers technology based school tra...,"Smita Deorah, Sumeet Mehta","GSV Ventures, Westbridge Capital",30000000,Series D
3,Bizongo,2015,Mumbai,B2B E-commerce,Bizongo is a business-to-business online marke...,"Aniket Deb, Ankit Tomar, Sachin Agrawal","CDC Group, IDG Capital",51000000,Series C
4,FypMoney,2021,Gurugram,FinTech,"FypMoney is Digital NEO Bank for Teenagers, em...",Kapil Banwari,"Liberatha Kallat, Mukesh Yadav, Dinesh Nagpal",2000000,Seed
...,...,...,...,...,...,...,...,...,...
1204,Gigforce,2019,Gurugram,Staffing & Recruiting,A gig/on-demand staffing company.,"Chirag Mittal, Anirudh Syal",Endiya Partners,3000000,Pre-series A
1205,Vahdam,2015,New Delhi,Food & Beverages,VAHDAM is among the world’s first vertically i...,Bala Sarda,IIFL AMC,20000000,Series D
1206,Leap Finance,2019,Bangalore,Financial Services,International education loans for high potenti...,"Arnav Kumar, Vaibhav Singh",Owl Ventures,55000000,Series C
1207,CollegeDekho,2015,Gurugram,EdTech,"Collegedekho.com is Student’s Partner, Friend ...",Ruchir Arora,"Winter Capital, ETS, Man Capital",26000000,Series B
1208,WeRize,2019,Bangalore,Financial Services,India’s first socially distributed full stack ...,"Vishal Chopra, Himanshu Gupta","3one4 Capital, Kalaari Capital",8000000,Series A

In [119]:
# REPLACING "undisclosed" WITH 'O'

startup_2021['Amount($)'] = startup_2021['Amount($)'].replace('undisclosed',0, regex = True)

In [121]:
# converting to float datatype

startup_2021['Amount($)']= pd.to_numeric(startup_2021['Amount($)'])

startup_2021['Amount($)'] = startup_2021['Amount($)'].apply(float)

# CLEANING OF THE STAGE COLUMN

In [132]:
startup_2021['Stage'].isna().sum()

423

In [133]:
startup_2021['Stage'].unique()

array(['Pre-series A', nan, 'Series D', 'Series C', 'Seed', 'Series B',
       'Series E', 'Pre-seed', 'Series A', 'Pre-series B', 'Debt',
       'Bridge', 'Seed+', 'Series F2', 'Series A+', 'Series G',
       'Series F', 'Series H', 'Series B3', 'PE', 'Series F1',
       'Pre-series A1', 'np.nan', 'Early seed', 'Series D1', '$6000000',
       'Seies A', 'Pre-series', 'Series A2', 'Series I'], dtype=object)

In [141]:
startup_2021.loc[startup_2021['Stage'] == '$6000000']

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage,Stag
674,MYRE Capital,2020,Mumbai,Commercial Real Estate,Democratising Real Estate Ownership,Own rent yielding commercial properties,Aryaman Vir,0.0,$6000000,$6000000

In [146]:
startup_2021.loc[startup_2021['Stage'] == '$6000000',['Amount($)','Stage']] = [6000000,'np.nan']

In [148]:
startup_2021['Stage'].unique()

array(['Pre-series A', 'Seed', 'Series D', 'Series C', 'Series B',
       'Series E', 'Pre-seed', 'Series A', 'Pre-series B', 'Debt',
       'Bridge', 'Seed+', 'Series F2', 'Series A+', 'Series G',
       'Series F', 'Series H', 'Series B3', 'PE', 'Series F1',
       'Pre-series A1', 'np.nan', 'Early seed', 'Series D1', 'nan',
       'Seies A', 'Pre-series', 'Series A2', 'Series I'], dtype=object)

In [150]:
# Filling NAN with fillna

startup_2021.Stage = startup_2021.Stage.fillna(startup_2021.Stage.mode()[0])

In [151]:
startup_2021.isna().sum()

Company/Brand    0
Founded          0
HeadQuarter      0
Sector           0
What it does     0
Founders         0
Investor         0
Amount($)        2
Stage            0
Stag             0
dtype: int64

In [159]:
startup_2021

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage,Year of Funding
0,Unbox Robotics,2019,Bangalore,AI startup,Unbox Robotics builds on-demand AI-driven ware...,"Pramod Ghadge, Shahid Memon","BEENEXT, Entrepreneur First",1200000.0,Pre-series A,2021
1,upGrad,2015,Mumbai,EdTech,UpGrad is an online higher education platform.,"Mayank Kumar, Phalgun Kompalli, Ravijot Chugh,...","Unilazer Ventures, IIFL Asset Management",120000000.0,Seed,2021
2,Lead School,2012,Mumbai,EdTech,LEAD School offers technology based school tra...,"Smita Deorah, Sumeet Mehta","GSV Ventures, Westbridge Capital",30000000.0,Series D,2021
3,Bizongo,2015,Mumbai,B2B E-commerce,Bizongo is a business-to-business online marke...,"Aniket Deb, Ankit Tomar, Sachin Agrawal","CDC Group, IDG Capital",51000000.0,Series C,2021
4,FypMoney,2021,Gurugram,FinTech,"FypMoney is Digital NEO Bank for Teenagers, em...",Kapil Banwari,"Liberatha Kallat, Mukesh Yadav, Dinesh Nagpal",2000000.0,Seed,2021
...,...,...,...,...,...,...,...,...,...,...
1204,Gigforce,2019,Gurugram,Staffing & Recruiting,A gig/on-demand staffing company.,"Chirag Mittal, Anirudh Syal",Endiya Partners,3000000.0,Pre-series A,2021
1205,Vahdam,2015,New Delhi,Food & Beverages,VAHDAM is among the world’s first vertically i...,Bala Sarda,IIFL AMC,20000000.0,Series D,2021
1206,Leap Finance,2019,Bangalore,Financial Services,International education loans for high potenti...,"Arnav Kumar, Vaibhav Singh",Owl Ventures,55000000.0,Series C,2021
1207,CollegeDekho,2015,Gurugram,EdTech,"Collegedekho.com is Student’s Partner, Friend ...",Ruchir Arora,"Winter Capital, ETS, Man Capital",26000000.0,Series B,2021
1208,WeRize,2019,Bangalore,Financial Services,India’s first socially distributed full stack ...,"Vishal Chopra, Himanshu Gupta","3one4 Capital, Kalaari Capital",8000000.0,Series A,2021

In [157]:

startup_2021['Year of Funding'] = '2021'

In [158]:
startup_2021

,Company/Brand,Founded,HeadQuarter,Sector,What it does,Founders,Investor,Amount($),Stage,Year of Funding
0,Unbox Robotics,2019,Bangalore,AI startup,Unbox Robotics builds on-demand AI-driven ware...,"Pramod Ghadge, Shahid Memon","BEENEXT, Entrepreneur First",1200000.0,Pre-series A,2021
1,upGrad,2015,Mumbai,EdTech,UpGrad is an online higher education platform.,"Mayank Kumar, Phalgun Kompalli, Ravijot Chugh,...","Unilazer Ventures, IIFL Asset Management",120000000.0,Seed,2021
2,Lead School,2012,Mumbai,EdTech,LEAD School offers technology based school tra...,"Smita Deorah, Sumeet Mehta","GSV Ventures, Westbridge Capital",30000000.0,Series D,2021
3,Bizongo,2015,Mumbai,B2B E-commerce,Bizongo is a business-to-business online marke...,"Aniket Deb, Ankit Tomar, Sachin Agrawal","CDC Group, IDG Capital",51000000.0,Series C,2021
4,FypMoney,2021,Gurugram,FinTech,"FypMoney is Digital NEO Bank for Teenagers, em...",Kapil Banwari,"Liberatha Kallat, Mukesh Yadav, Dinesh Nagpal",2000000.0,Seed,2021
...,...,...,...,...,...,...,...,...,...,...
1204,Gigforce,2019,Gurugram,Staffing & Recruiting,A gig/on-demand staffing company.,"Chirag Mittal, Anirudh Syal",Endiya Partners,3000000.0,Pre-series A,2021
1205,Vahdam,2015,New Delhi,Food & Beverages,VAHDAM is among the world’s first vertically i...,Bala Sarda,IIFL AMC,20000000.0,Series D,2021
1206,Leap Finance,2019,Bangalore,Financial Services,International education loans for high potenti...,"Arnav Kumar, Vaibhav Singh",Owl Ventures,55000000.0,Series C,2021
1207,CollegeDekho,2015,Gurugram,EdTech,"Collegedekho.com is Student’s Partner, Friend ...",Ruchir Arora,"Winter Capital, ETS, Man Capital",26000000.0,Series B,2021
1208,WeRize,2019,Bangalore,Financial Services,India’s first socially distributed full stack ...,"Vishal Chopra, Himanshu Gupta","3one4 Capital, Kalaari Capital",8000000.0,Series A,2021

In [160]:
file_name = "cleaned_2021.csv"

startup_2021.to_csv(file_name)